"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['InstaBot.py']
DATA_FILES = ['/Users/fmaillet/my_bot/files/hashtag_list.txt',
              '/Users/fmaillet/my_bot/font/Capture_it.ttf',
              '/Users/fmaillet/my_bot/font/zekton_rg.ttf',
              'chromedriver']
OPTIONS = OPTIONS = {'argv_emulation': True,
                     'packages': ['selenium']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
